/*
 * Copyright (c) 2014, Allwinner Technology Co., Ltd. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SUNXI_CCU_H
#define SUNXI_CCU_H

#include "autoGenHeaders/ccmu.h"
#define SUNXI_CCU_SEC_SWITCH_REG	(SUNXI_CCU_BASE + CCMU_SEC_SWITCH_REG)

#define SUNXI_R_PRCM_SEC_SWITCH_REG	(SUNXI_R_PRCM_BASE + 0x0290)

#define SUNXI_UART_BGR_REG (SUNXI_CCU_BASE + UART0_BGR_REG)

#define SUNXI_UART_CLK_REG (SUNXI_CCU_BASE + APB_UART_CLK_REG)
#define SUNXI_UART_CLK_SRC_SEL_HOSC APB_UART_CLK_REG_CLK_SRC_SEL_HOSC
#define SUNXI_UART_CLK_SRC_SEL_PERI0_600M_BUS APB_UART_CLK_REG_CLK_SRC_SEL_PERI0_600M_BUS
#define SUNXI_UART_CLK_SRC_SEL_PERI0_480M_BUS APB_UART_CLK_REG_CLK_SRC_SEL_PERI0_480M_BUS

#endif /* SUNXI_CCU_H */
